// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolderPair(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddFolderPair'](arg1, arg2, arg3, arg4);
}

export function GetFolderPairs() {
  return window['go']['main']['App']['GetFolderPairs']();
}

export function RemoveFolderPair(arg1) {
  return window['go']['main']['App']['RemoveFolderPair'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function ToggleFolderPair(arg1, arg2) {
  return window['go']['main']['App']['ToggleFolderPair'](arg1, arg2);
}

export function UpdateFolderPair(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateFolderPair'](arg1, arg2, arg3, arg4, arg5);
}
