// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFolderPair(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function GetFolderPairs():Promise<Array<main.WatcherConfig>>;

export function RemoveFolderPair(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function ToggleFolderPair(arg1:string,arg2:boolean):Promise<void>;

export function UpdateFolderPair(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<void>;
